### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by CBaymax** [KrzyHonk/bpmn-python#40]
When I run the `csv_import_test.py`, got the error.

```
======================================================================
ERROR: test_csv_import_csv_export (__main__.CsvExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\csv_import_test.py", line 25, in test_csv_import_csv_export
    bpmn_graph.load_diagram_from_csv_file(os.path.abspath(self.input_directory + process + ".csv"))
  File "D:\Program\Anaconda3\lib\site-packages\bpmn_python\bpmn_diagram_rep.py", line 91, in load_diagram_from_csv_file
    bpmn_csv_import.BpmnDiagramGraphCSVImport.load_diagram_from_csv(filepath, self)
  File "D:\Program\Anaconda3\lib\site-packages\bpmn_python\bpmn_process_csv_import.py", line 602, in load_diagram_from_csv
    BpmnDiagramGraphCSVImport.import_nodes(process_dict, bpmn_diagram, sequence_flows)
  File "D:\Program\Anaconda3\lib\site-packages\bpmn_python\bpmn_process_csv_import.py", line 635, in import_nodes
    fill_graph_connections(process_dict, bpmn_diagram, sequence_flows)
  File "D:\Program\Anaconda3\lib\site-packages\bpmn_python\bpmn_process_csv_import.py", line 479, in fill_graph_connections
    add_connection(node_id, successor_node_id, process_dict, bpmn_diagram, sequence_flows)
  File "D:\Program\Anaconda3\lib\site-packages\bpmn_python\bpmn_process_csv_import.py", line 339, in add_connection
    add_edge(from_node_id, to_node_id, process_dict, diagram_graph, sequence_flows)
  File "D:\Program\Anaconda3\lib\site-packages\bpmn_python\bpmn_process_csv_import.py", line 314, in add_edge
    bpmn_diagram.diagram_graph.edge[from_node_id][to_node_id][consts.Consts.id] = flow_id
AttributeError: 'Graph' object has no attribute 'edge'
```

**Comment by CBaymax** [comment]
Don't install bpmn_python by pip，but use the source code directly can avoid this error.  :D
